### ISSUE TITLE
ModelSEED/Documentation Page

### ISSUE THREAD

**Issue by chian** [ModelSEED/Documentation#1]
@nconrad Looking into the faq.md file under ModelSEED/Documentation, I noticed that you state all methods are the same as in the original nature paper and that all results should be the same as those produced by the original article. That doesn't strike me as very true given some of the changes to the underlying data we made during ProbAnno development, so I'm not sure if that should be up there. Also, some of the underlying algorithms have changed, for example the gapfill is now faster. Much of the other stuff will change soon.

Putting that aside, I'm not sure where ProbModelSEED fits into this faq's page. Given that it seems like ModelSEED is intended to recapitulate the original nature biotech paper, it doesn't seem to be appropriate to include ProbModelSEED here. Is there going to be a separate ProbModelSEED page? Or will ProbModelSEED eventually replace?

**Comment by nconrad** [comment]
This has been corrected and expanded on.  I deployed what's currently in master for the time being.  Note: these FAQs and any other documentation we want will soon have a home that can be reached from the home page without auth.
